#!/bin/bash

user_exist() {
    local user=$1
    local exist=$(grep "\<$user\>" /etc/passwd)

    if [ -z "$exist" ]
    then
	exit 1
    else
	exit 0
    fi
}

prepare_chroot() {
    if [ -e "$chrootdir" -a "$force" != "true" ]
    then
	echo "$chrootdir is exist. If you wants repeat preparing chroot directory use force (-f) option"
	return 1
    elif [ -e "$chrootdir" -a "$force" = "true" ]
    then
	oldchroot=$chrootdir-$(date +"%y%m%d-%H%M")
	mv $chrootdir $oldchroot
    fi

    # create basic directory
    echo "Default chroot directory will be created [$chrootdir]. If you want change this default use \"-d directory_name\""
    mkdir -p $chrootdir/{dev,usr,bin,sbin,lib,lib64,home,etc} 2> /dev/null
    mkdir -p $chrootdir/usr/{bin,sbin,lib} 2> /dev/null
    mkdir $chrootdir/lib/x86_64-linux-gnu 2> /dev/null
    [ ! -z "$oldchroot" ] && cp -r $oldchroot/home/* $chrootdir/home/
    echo "Create basic directory .... pass"

    
    # create necessary
    mknod $chrootdir/dev/null c 1 3
    mknod $chrootdir/dev/tty c 5 0
    mknod $chrootdir/dev/zero c 1 5
    mknod $chrootdir/dev/random c 1 8
    echo "Create minimum character device .... pass"
    
    # copy bash and its dependencies
    cp /bin/bash $chrootdir/bin/
    cp /lib/x86_64-linux-gnu/{libc.so.6,libtinfo.so.5,libdl.so.2} $chrootdir/lib/
    cp /lib64/ld-linux-x86-64.so.2 $chrootdir/lib64/
    echo "Copy bash and depencies .... pass"
    
    # bash config
    cp /etc/bash.bashrc $chrootdir/etc/
    cp /etc/profile $chrootdir/etc/
    cp -r /etc/profile.d $chrootdir/etc/
    echo "Copy bash and profile config .... pass"
    
    # copy nsswitch config and library
    cp /etc/passwd $chrootdir/etc/
    cp /etc/group $chrootdir/etc/
    cp /etc/nsswitch.conf $chrootdir/etc/
    cp -a /lib/x86_64-linux-gnu/{libnss_compat.so.2,libnss_dns.so.2,libnss_files.so.2,libnsl.so.1} $chrootdir/lib/x86_64-linux-gnu/
    cp $(readlink -f /lib/x86_64-linux-gnu/{libnss_compat.so.2,libnss_dns.so.2,libnss_files.so.2,libnsl.so.1}) $chrootdir/lib/x86_64-linux-gnu/
    cp /usr/bin/groups $chrootdir/usr/bin/
    cp /usr/bin/whoami $chrootdir/usr/bin/
    cd $chrootdir/lib/x86_64-linux-gnu
    echo "Copy nsswitch config and libraries .... pass"
    
    cp /usr/bin/id $chrootdir/usr/bin/
    cp /lib/x86_64-linux-gnu/{libselinux.so.1,libpcre.so.3,libpthread.so.0} $chrootdir/lib/
    
    # copy utils
    cp /bin/{ls,cp,rm,mv,cat,nano} $chrootdir/bin/
    echo "Copy commands and utilities .... pass"

}

usage() {
    echo -e "Usage chroot_user [-u username][-d chroot_directory]\n      chroot_user -i\n"

    return 0
}

#mv /home/$USER $chrootdir/
while getopts :ifu:d:t: opt
do
	case $opt in 
	    i) interactive=true
		;;
	    u) username="$opt"
		;;
	    d) chroot="$opt"
		;;
	    t) type="$opt"
		;;
	    f) force=true
		;;
	    *) usage
		;;
	esac
done

chrootdir=${chroot:-/home/chroot}

if [[ "$interactive" = "true" ]] && [ ! -z "$username" -o  ! -z "$type" -o ! -z "$chroot" ]
then
    echo "[ERROR] Dont use \"-i\" with any other argument"
    usage
    exit 1
elif [ "$interactive" = "true" ]
then
    echo N
fi

prepare_chroot
exit 0
