#!/bin/bash

# This script based on Backup and Recovery boot that cat find below link
# https://books.google.com/books?id=QgpIAgAAQBAJ&printsec=frontcover#v=onepage&q&f=false
# backup home

# Exit immediately if a command exits with a non-zero status.
set -e

# backup home
HOME="/home/peyk"

hourly() {
	rsync -av --delete --chown=peyk:peyk --link-dest=../dunro-backup-1 root@192.168.20.2:/home/www-data/. $HOME/dunro-backup/

	[ -d "$HOME/dunro-backup-24" ] && [ ! -d "$HOME/dunro-backup-tmp" ] &&  mv $HOME/dunro-backup-24 $HOME/dunro-backup-tmp
	for I in {24..1}
	do
		if [ "$I" == "1" ] 
		then
			break
		fi
	
		J=$I
		((J--))
		filesrc="$HOME/dunro-backup-$J"
		filedst="$HOME/dunro-backup-$I"
	
		[ -d "$filesrc" ] && [ ! -e "$filedst" ] && mv $filesrc $filedst
	done
	
	[ ! -d "$HOME/dunro-backup-1" -a ! -e "$HOME/dunro-backup-1" ] && mv $HOME/dunro-backup $HOME/dunro-backup-1	
	[ -d "$HOME/dunro-backup-tmp" -a ! -e "$HOME/dunro-backup" ] && mv $HOME/dunro-backup-tmp $HOME/dunro-backup
	[ -d "$HOME/dunro-backup-1" ] && touch $HOME/dunro-backup-1

	return 0
}

daily() {
	rsync -av --delete --chown=peyk:peyk --link-dest=../dunro-backup-1  /home/peyk/dunro-backup-1/. /home/peyk/daily/dunro-backup/

	[ -d "$HOME/daily/dunro-backup-7" ] && [ ! -d "$HOME/daily/dunro-backup-tmp" ] && mv $HOME/daily/dunro-backup-7 $HOME/daily/dunro-backup-tmp
        for I in {7..1}
        do
                if [ "$I" == "1" ]
                then
                        break
                fi

                J=$I
                ((J--))
                filesrc="$HOME/daily/dunro-backup-$J"
                filedst="$HOME/daily/dunro-backup-$I"

		[ -d "$filesrc" ] && [ ! -e "$filedst" ] && mv $filesrc $filedst
        done

	[ -d "$HOME/daily/dunro-backup" ] && [ ! -e "$HOME/daily/dunro-backup-1" ] && mv $HOME/daily/dunro-backup $HOME/daily/dunro-backup-1
	[ -d "$HOME/daily/dunro-backup-tmp" ] && [ ! -e "$HOME/daily/dunro-backup" ] &&  mv $HOME/daily/dunro-backup-tmp $HOME/daily/dunro-backup
	
	return 0

}


weekly() {
	rsync -av --delete --chown=peyk:peyk --link-dest=../dunro-backup-1  /home/peyk/dunro-backup-1/. /home/peyk/weekly/dunro-backup/

	[ -d "$HOME/weekly/dunro-backup-4" ] && [ ! -e "$HOME/weekly/dunro-backup-tmp" ] && mv $HOME/weekly/dunro-backup-4 $HOME/weekly/dunro-backup-tmp
        for I in {4..1}
        do
                if [ "$I" == "1" ]
                then
                        break
                fi

                J=$I
                ((J--))
                filesrc="$HOME/weekly/dunro-backup-$J"
                filedst="$HOME/weekly/dunro-backup-$I"

		[ -d "$filesrc" ] && [ ! -e "$filedst" ] && mv $filesrc $filedst
        done

		[ -d "$HOME/weekly/dunro-backup" ] && [ ! -e "$HOME/weekly/dunro-backup-1" ] && mv $HOME/weekly/dunro-backup $HOME/weekly/dunro-backup-1
		[ -d "$HOME/weekly/dunro-backup-tmp" ] && [ ! -e "$HOME/weekly/dunro-backup" ] &&  mv $HOME/weekly/dunro-backup-tmp $HOME/weekly/dunro-backup
	
	return 0

}

if [ "$1" == "hourly" ]
then
	hourly
elif [ "$1" == "daily" ]
then
	daily
elif [ "$1" == "weekly" ]
then
	weekly
fi

exit 0
